### ISSUE TITLE
Add Update For Node

### ISSUE THREAD

**Issue by jeremypm** [INSYEN/SphereWebFrontend#4]
I'd like to add a node update message.

The request should be formatted (to the backend) as a json blob which complies with the following syntax:
action:updateNode
nodes:An optional array of nodes to check

The response will appear as follows:
nodeStatus: A list containing key:value pairs, where the key is the node number and the value is one of the following statuses: valid,invalid. A "valid" value should cause the node to appear blue, and "invalid" should appear as red.

This message can be sent once every few seconds (1-5).

**Comment by paramarco** [comment]
done! please test it! the period/frequency to define how often the request should be made, it is defined as a global setting in ./config/config.js

**Comment by jeremypm** [comment]
Just found one issue, in the node number array, the individual nodes are being passed as strings.

**Comment by paramarco** [comment]
I've just made a new commit to fix the problem ea5b8fdd5a57b3632690a021ed569f33986265c1, please test it again.
